version: '3'

services:
  php:
    build:
      context: ./.docker/php
      args:
        UID: ${UID}
        GID: ${GID}
    user: '${UID}:${GID}'
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www/
    networks:
      - app

  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: "serverName=php"
    networks:
      - app

  mysql:
    image: mysql:8.0.32-debian
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - app

networks:
  app:

volumes:
  db:
