version: '3'

services:
  php:
    build:
      context: ./.docker/php
      args:
        UID: ${UID}
        GID: ${GID}
    user: '${UID}:${GID}'
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www/
    networks:
      - app

  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: "serverName=php"
    networks:
      - app

  mysql:
    image: mysql:8.0.32-debian
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - xpack.security.enabled=false
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3.10.20-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    networks:
      - app

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.7.0
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    networks:
#      - app

networks:
  app:

volumes:
  db:
  es:
