version: '3'

services:
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/
    networks:
      - app
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

networks:
  app: