services:
  # INFRASTRUCTURE
  Jgrc\Shop\Acceptance\Context\Infrastructure\SymfonyHttpContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\SymfonyHttpContext
    arguments:
      - '@kernel'
    public: true

  Jgrc\Shop\Acceptance\Context\Infrastructure\SymfonyCliContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\SymfonyCliContext
    arguments:
      - '@kernel'
    public: true

  Jgrc\Shop\Acceptance\Context\Infrastructure\DataBaseContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\DataBaseContext
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%env(resolve:DATABASE_NAME)%'
    public: true

  Jgrc\Shop\Acceptance\Context\Infrastructure\ElasticContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\ElasticContext
    arguments:
      - '@es.client'
      - '%env(resolve:ELASTIC_PRODUCT_INDEX)%'
    public: true

  Jgrc\Shop\Acceptance\Context\Infrastructure\ClockContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\ClockContext
    arguments:
      - '@clock'
    public: true

  Jgrc\Shop\Acceptance\Context\Infrastructure\RandomContext:
    class: Jgrc\Shop\Acceptance\Context\Infrastructure\RandomContext
    public: true

  # DOMAIN
  Jgrc\Shop\Acceptance\Context\Domain\CategoryContext:
    class: Jgrc\Shop\Acceptance\Context\Domain\CategoryContext
    arguments:
      - '@command.bus'
      - '@category.repository'
    public: true

  Jgrc\Shop\Acceptance\Context\Domain\ProductContext:
    class: Jgrc\Shop\Acceptance\Context\Domain\ProductContext
    arguments:
      - '@command.bus'
      - '@product.repository'
    public: true

  Jgrc\Shop\Acceptance\Context\Domain\FilterContext:
    class: Jgrc\Shop\Acceptance\Context\Domain\FilterContext
    arguments:
      - '@command.bus'
      - '@filter-group.repository'
      - '@filter.repository'
    public: true