services:

  # DOCTRINE
  category.repository:
    class: Jgrc\Shop\Infrastructure\Persistence\Orm\Repository\DoctrineCategoryRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  # COMMAND HANDLERS
  create.category.handler:
    class: Jgrc\Shop\Application\Category\CreateCategoryHandler
    arguments:
      - '@category.repository'
    tags:
      - { name: messenger.message_handler, bus: messenger.command.bus }

  # CLI COMMANDS
  cli.category.create:
    class: Jgrc\Shop\Infrastructure\Ui\Cli\Category\CreateCategoryCli
    arguments:
      - '@command.bus'
      - '@clock'
    tags:
      - console.command
