services:

  # KERNEL
  listener.kernel.view:
    class: Jgrc\Shop\Infrastructure\Symfony\Listener\KernelViewListener
    arguments:
      - '@messenger.transformer.bus'
    tags:
      - kernel.event_listener

  listener.kernel.exception:
    class: Jgrc\Shop\Infrastructure\Symfony\Listener\KernelExceptionListener
    arguments:
      - '@messenger.transformer.bus'
    tags:
      - kernel.event_listener

  # SYSTEM
  clock:
    class: Jgrc\Shop\Infrastructure\SystemClock

  # ELASTIC
  es.factory:
    class: Jgrc\Shop\Infrastructure\Persistence\Es\ClientFactory

  es.client:
    class: Elastic\Elasticsearch\Client
    factory: ['@es.factory', create]
    arguments:
      - '%env(resolve:ELASTIC_URLS)%'

  # BUSES
  command.bus:
    class: Jgrc\Shop\Infrastructure\Bus\MessengerCommandBus
    arguments:
      - '@messenger.command.bus'

  query.bus:
    class: Jgrc\Shop\Infrastructure\Bus\MessengerQueryBus
    arguments:
      - '@messenger.query.bus'

  throw.exception.middleware:
    class: Jgrc\Shop\Infrastructure\Bus\MessengerExceptionMiddleware

  # TRANSFORMERS
  not-found-http.transformer:
    class: Jgrc\Shop\Infrastructure\Symfony\Http\Transformer\Common\NotFoundHttpExceptionTransformer
    tags:
      - { name: messenger.message_handler, bus: messenger.transformer.bus }

  invalid-argument.transformer:
    class: Jgrc\Shop\Infrastructure\Symfony\Http\Transformer\Common\InvalidArgumentExceptionTransformer
    tags:
      - { name: messenger.message_handler, bus: messenger.transformer.bus }

  lazy-assertion.transformer:
    class: Jgrc\Shop\Infrastructure\Symfony\Http\Transformer\Common\LazyAssertionExceptionTransformer
    tags:
      - { name: messenger.message_handler, bus: messenger.transformer.bus }