services:

  # DOCTRINE
  product.repository:
    class: Jgrc\Shop\Infrastructure\Persistence\Orm\Repository\DoctrineProductRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  product.projector:
    class: Jgrc\Shop\Infrastructure\Persistence\Dbal\Projector\DbalProductProjector
    arguments:
      - '@doctrine.dbal.default_connection'

  # ELASTIC
  product.store:
    class: Jgrc\Shop\Infrastructure\Persistence\Es\ElasticProductStore
    arguments:
      - '@es.client'
      - '%env(resolve:ELASTIC_PRODUCT_INDEX)%'

  product.view:
    class: Jgrc\Shop\Infrastructure\Persistence\Es\ElasticProductView
    arguments:
      - '@es.client'
      - '%env(resolve:ELASTIC_PRODUCT_INDEX)%'

  # COMMAND HANDLERS
  create.product.handler:
    class: Jgrc\Shop\Application\Product\CreateProductHandler
    arguments:
      - '@category.repository'
      - '@product.repository'
    tags:
      - { name: messenger.message_handler, bus: messenger.command.bus }

  add.product-filters.handler:
    class: Jgrc\Shop\Application\Product\AddProductFiltersHandler
    arguments:
      - '@product.repository'
      - '@filter.repository'
    tags:
      - { name: messenger.message_handler, bus: messenger.command.bus }

  project.product.handler:
    class: Jgrc\Shop\Application\Product\ProjectProductHandler
    arguments:
      - '@product.projector'
      - '@product.store'
      - '@clock'
    tags:
      - { name: messenger.message_handler, bus: messenger.command.bus }

  # QUERY HANDLERS
  get.product.by-id:
    class: Jgrc\Shop\Application\Product\GetProductByIdHandler
    arguments:
      - '@product.view'
    tags:
      - { name: messenger.message_handler, bus: messenger.query.bus }

  # CLI COMMANDS
  cli.product.create:
    class: Jgrc\Shop\Infrastructure\Ui\Cli\Product\CreateProductCli
    arguments:
      - '@command.bus'
      - '@clock'
    tags:
      - console.command

  cli.product.add-filters:
    class: Jgrc\Shop\Infrastructure\Ui\Cli\Product\AddProductFiltersCli
    arguments:
      - '@command.bus'
    tags:
      - console.command

  cli.product.project:
    class: Jgrc\Shop\Infrastructure\Ui\Cli\Product\ProjectProductCli
    arguments:
      - '@command.bus'
    tags:
      - console.command

  # CONTROLLERS
  http.product.get-by-id:
    class: Jgrc\Shop\Infrastructure\Ui\Http\Product\GetProductByIdController
    arguments:
      - '@query.bus'
    tags:
      - controller.service_arguments

  # TRANSFORMERS
  product.transformer:
    class: Jgrc\Shop\Infrastructure\Symfony\Http\Transformer\Product\ProductProjectionTransformer
    tags:
      - { name: messenger.message_handler, bus: messenger.transformer.bus }

  product-not-found.transformer:
    class: Jgrc\Shop\Infrastructure\Symfony\Http\Transformer\Product\ProductNotFoundTransformer
    tags:
      - { name: messenger.message_handler, bus: messenger.transformer.bus }
